services:
  - type: web
    name: evrenwebsite
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn evren_academy.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false