# Generated by Django 6.0.5 on 2026-05-18 09:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_heroslide_options_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Evren Academy', max_length=255)),
                ('intro', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mission', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('vision', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('history', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('admission_overview', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('eligibility', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('career_overview', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institution Profile',
                'verbose_name_plural': 'Institution Profile',
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('associate', 'Associate'), ('advisory_board', 'Advisory Board'), ('faculty', 'Faculty'), ('principal', 'Principal')], default='faculty', max_length=30),
        ),
    ]
