# Generated by Django 6.0.5 on 2026-05-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_institutionprofile_teammember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copyright',
            field=models.CharField(blank=True, default='Copyright (c) Evren Academy. All rights reserved.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_about',
            field=models.TextField(blank=True, default='Premium educational institution dedicated to excellence in education.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_map_embed',
            field=models.TextField(blank=True, help_text='Optional Google Maps iframe embed code for the contact page.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_autoplay_ms',
            field=models.PositiveIntegerField(default=5500, help_text='Hero slide autoplay delay in milliseconds.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_media_fit',
            field=models.CharField(choices=[('cover', 'Fill hero area (recommended)'), ('contain', 'Show full media without cropping')], default='cover', help_text='Choose how hero images and videos should fill the slide.', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_overlay_opacity',
            field=models.DecimalField(decimal_places=2, default=0.55, help_text='Dark overlay strength from 0.00 to 1.00.', max_digits=3),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_transition_ms',
            field=models.PositiveIntegerField(default=1400, help_text='Hero dissolve transition speed in milliseconds.'),
        ),
    ]
