# Generated by Django 6.0.5 on 2026-05-18 11:20

import ckeditor_uploader.fields
from django.db import migrations, models


def copy_legacy_team_fields(apps, schema_editor):
    TeamMember = apps.get_model('core', 'TeamMember')
    category_map = {
        'advisory_board': 'advisory',
        'principal': 'management',
        'associate': 'management',
        'faculty': 'faculty',
    }
    for member in TeamMember.objects.all():
        member.full_name = member.full_name or member.name
        member.designation = member.designation or member.title
        member.team_category = category_map.get(member.role, member.team_category or 'faculty')
        member.display_order = member.display_order or member.order
        member.short_bio = member.short_bio or member.bio
        member.save(update_fields=[
            'full_name',
            'designation',
            'team_category',
            'display_order',
            'short_bio',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_copyright_sitesettings_footer_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ready to begin your learning journey?', max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('button_text', models.CharField(default='Apply for Admission', max_length=100)),
                ('button_link', models.CharField(default='/admissions/', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cta/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CTA Section',
                'verbose_name_plural': 'CTA Section',
            },
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='popups/')),
                ('button_text', models.CharField(blank=True, default='Learn More', max_length=100)),
                ('button_url', models.CharField(blank=True, max_length=255)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('show_once_per_session', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Popup',
                'verbose_name_plural': 'Popups',
                'ordering': ['display_order', '-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['display_order', 'order'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammember',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='short_bio',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team_category',
            field=models.CharField(choices=[('advisory', 'Advisory Board'), ('management', 'Management Team'), ('faculty', 'Faculty Team'), ('staff', 'Staff')], default='faculty', max_length=30),
        ),
        migrations.RunPython(copy_legacy_team_fields, migrations.RunPython.noop),
    ]
