# Generated by Django 6.0.5 on 2026-05-18 11:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='faqs',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Add FAQs as headings and paragraphs or as a list.'),
        ),
        migrations.AddField(
            model_name='course',
            name='fees',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/hero/'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('foundation', 'Foundation'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='overview',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
