# Generated by Django 6.0.5 on 2026-05-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.CharField(max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
