# Generated by Django 6.0.5 on 2026-05-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionenquiry',
            name='campus_preference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
