# Generated by Django 6.0.5 on 2026-05-18 09:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='campus_type',
            field=models.CharField(choices=[('boys', 'Boys Campus'), ('girls', 'Girls Campus'), ('general', 'General Campus')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='facilities_available',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='infrastructure_details',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
